### ISSUE TITLE
Add CI for running tests

### ISSUE THREAD

**Issue by agonzalezro** [agonzalezro/botella#1]
The command to run:

```
go test $(glide novendor)
```

It will require docker installed in the machine.

**Comment by Nols1000** [comment]
As I understand you want to do automatic testing where the testing environment has docker available, right? I think travis would work fine (https://docs.travis-ci.com/user/docker/). If you'd like I can add a simple travis pipeline, that will run tests.

**Comment by agonzalezro** [comment]
Yes: run the tests, integrate them with the PRs and show a badge on the README.

I would prefer to go with CircleCI since I am using it for other projects, but happy with Travis as well.

**Comment by Nols1000** [comment]
I have created a PR (#14) for this issue with CircleCI.
